### PR TITLE
Make ? open help too, and close it also with ? or h

### PR DESCRIPTION
**Pull request by abitrolly**
Add ? for invoking help, and let the same key close it.

Fixes https://github.com/altsem/gitu/issues/124

### CODE REVIEW

**Comment by altsem** [comment]
Hey @abitrolly!

If think this'd make sense, if it were not for the plans to later add search functionality - which is commonly bound to `/` and `?`.

As found in: https://github.com/altsem/gitu/issues/5

**Comment by abitrolly** [comment]
@altsem left some `?` binding related comments in https://github.com/altsem/gitu/issues/5#issuecomment-2471565549

**Comment by altsem** [comment]
I did some googling. I think Doom Emacs uses `?` for the help menu (haven't confirmed this).
Is that the case for other evil-mode ways of using Magit?

If that is the case, it feels like a no-brainer to copy this behaviour.

**Comment by abitrolly** [comment]
@altsem Magit itself uses `?` - https://github.com/niyumard/Doom-Emacs-Cheat-Sheet?tab=readme-ov-file#magit

**Comment by altsem** [comment]
Let's merge this then :)
I noticed h -> h or ? -> ? opens up a manual in Doom. But we don't have one yet, so seems fine.

Thanks for talking some sense into me.

**Pull request merged**
